# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/rodrigo/.local/lib/python3.10/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/rodrigo/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rodrigo/Documents/Personal/ThreadLib

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rodrigo/Documents/Personal/ThreadLib

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/rodrigo/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/rodrigo/.local/lib/python3.10/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rodrigo/Documents/Personal/ThreadLib/CMakeFiles /home/rodrigo/Documents/Personal/ThreadLib//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rodrigo/Documents/Personal/ThreadLib/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

main.o: main.cc.o
.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i
.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s
.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cc.s
.PHONY : main.cc.s

source/cpu.o: source/cpu.cc.o
.PHONY : source/cpu.o

# target to build an object file
source/cpu.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/source/cpu.cc.o
.PHONY : source/cpu.cc.o

source/cpu.i: source/cpu.cc.i
.PHONY : source/cpu.i

# target to preprocess a source file
source/cpu.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/source/cpu.cc.i
.PHONY : source/cpu.cc.i

source/cpu.s: source/cpu.cc.s
.PHONY : source/cpu.s

# target to generate assembly for a file
source/cpu.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/source/cpu.cc.s
.PHONY : source/cpu.cc.s

source/debug.o: source/debug.cc.o
.PHONY : source/debug.o

# target to build an object file
source/debug.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/source/debug.cc.o
.PHONY : source/debug.cc.o

source/debug.i: source/debug.cc.i
.PHONY : source/debug.i

# target to preprocess a source file
source/debug.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/source/debug.cc.i
.PHONY : source/debug.cc.i

source/debug.s: source/debug.cc.s
.PHONY : source/debug.s

# target to generate assembly for a file
source/debug.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/source/debug.cc.s
.PHONY : source/debug.cc.s

source/semaphore.o: source/semaphore.cc.o
.PHONY : source/semaphore.o

# target to build an object file
source/semaphore.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/source/semaphore.cc.o
.PHONY : source/semaphore.cc.o

source/semaphore.i: source/semaphore.cc.i
.PHONY : source/semaphore.i

# target to preprocess a source file
source/semaphore.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/source/semaphore.cc.i
.PHONY : source/semaphore.cc.i

source/semaphore.s: source/semaphore.cc.s
.PHONY : source/semaphore.s

# target to generate assembly for a file
source/semaphore.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/source/semaphore.cc.s
.PHONY : source/semaphore.cc.s

source/system.o: source/system.cc.o
.PHONY : source/system.o

# target to build an object file
source/system.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/source/system.cc.o
.PHONY : source/system.cc.o

source/system.i: source/system.cc.i
.PHONY : source/system.i

# target to preprocess a source file
source/system.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/source/system.cc.i
.PHONY : source/system.cc.i

source/system.s: source/system.cc.s
.PHONY : source/system.s

# target to generate assembly for a file
source/system.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/source/system.cc.s
.PHONY : source/system.cc.s

source/thread.o: source/thread.cc.o
.PHONY : source/thread.o

# target to build an object file
source/thread.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/source/thread.cc.o
.PHONY : source/thread.cc.o

source/thread.i: source/thread.cc.i
.PHONY : source/thread.i

# target to preprocess a source file
source/thread.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/source/thread.cc.i
.PHONY : source/thread.cc.i

source/thread.s: source/thread.cc.s
.PHONY : source/thread.s

# target to generate assembly for a file
source/thread.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/source/thread.cc.s
.PHONY : source/thread.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... source/cpu.o"
	@echo "... source/cpu.i"
	@echo "... source/cpu.s"
	@echo "... source/debug.o"
	@echo "... source/debug.i"
	@echo "... source/debug.s"
	@echo "... source/semaphore.o"
	@echo "... source/semaphore.i"
	@echo "... source/semaphore.s"
	@echo "... source/system.o"
	@echo "... source/system.i"
	@echo "... source/system.s"
	@echo "... source/thread.o"
	@echo "... source/thread.i"
	@echo "... source/thread.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

